<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>UriCredentialParser</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>UriCredentialParser</AssemblyName>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageId>ciu-parser</PackageId>
        <Title>Uri Credential Parser</Title>
        <Authors>Winner-Timothy Bolorunduro </Authors>
        <Description>A lightweight .NET library for parsing credentials from URLs and converting them into structured connection strings for PostgreSQL and MongoDB.</Description>
        <Copyright>©2024-2026, Bolorunduro Winner-Timothy. All Rights reserved.</Copyright>
        <PackageProjectUrl>https://github.com/bolorundurowb/UriCredentialParser</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/bolorundurowb/UriCredentialParser/blob/master/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/bolorundurowb/UriCredentialParser</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>uri, url, credentials, connection-string, parser, postgres, npgsql, mongodb, dotnet, csharp, authentication, parsing, utility</PackageTags>
        <Version>3.0.0</Version>
        <PackageReleaseNotes>- changes asembly and lib name to be more intuitive. 
- Update target framework to adjust to .NEt recommendations</PackageReleaseNotes>
        <AssemblyVersion>3.0.0</AssemblyVersion>
        <FileVersion>3.0.0</FileVersion>
        <NeutralLanguage>en-NG</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
